FROM golang:1.24.3-alpine3.21 AS builder

# 
ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /usr/local/source/

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./cmd/calc-app ./cmd
COPY ./pkg ./pkg
COPY ./internal ./internal

# билд без флагов отладки
RUN go build -ldflags="-s -w" -o /usr/local/bin/app ./cmd/

FROM alpine:3.21

USER 1000:1000

COPY --from=builder /usr/local/bin/app /app

ENTRYPOINT [ "/app" ]